version: '3.4'

services:
  app: 
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - .:/usr/app
    depends_on:
      - db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5433
      DATABASE_URL: db
      PORT: 3000
  db:
    container_name: 'database-node'
    image: postgres:15.1-alpine
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: teddy
    volumes: 
      - /pgdata:/var/lib/postgres/data
volumes:
  db:
    driver: local